# Generated by Django 4.2.11 on 2025-09-21 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_create_accelerator_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='legacy_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='payload',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uuid',
        ),
    ]
