from typing import Any, TypeVar, Generic
from django.db.models import Model, QuerySet
from rest_framework.request import Request
from rest_framework.response import Response

_M = TypeVar("_M", bound=Model)

class ModelViewSet(Generic[_M]):
    def get_object(self) -> _M: ...
    def get_queryset(self) -> QuerySet[_M]: ...
    def create(self, request: Request, *args: Any, **kwargs: Any) -> Response: ...
    def update(self, request: Request, *args: Any, **kwargs: Any) -> Response: ...
    def partial_update(
        self, request: Request, *args: Any, **kwargs: Any
    ) -> Response: ...
    def destroy(self, request: Request, *args: Any, **kwargs: Any) -> Response: ...
