# Generated by Django 4.2.11 on 2025-07-30 20:30

import common.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(db_index=True, editable=False, verbose_name='Atualizado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('file', models.FileField(upload_to=common.models.get_attachment_upload_path, verbose_name='Arquivo')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('object_id', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(db_index=True, editable=False, verbose_name='Atualizado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('contents', models.TextField(verbose_name='Conteúdo')),
                ('object_id', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
    ]
