# Generated by Django 4.2.11 on 2025-07-31 14:00

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_initial'),
    ]

    operations = [
        TrigramExtension(),
        UnaccentExtension(),
    ]
