# Generated by Django 4.2.11 on 2025-09-21 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(db_index=True, editable=False, verbose_name='Atualizado em')),
                ('name', models.CharField(help_text='Nome do medicamento', max_length=200, verbose_name='Nome da medicação')),
                ('dosage', models.CharField(help_text='Dosagem prescrita (ex: 10mg, 1 comprimido)', max_length=100, verbose_name='Dosagem')),
                ('schedule_time', models.TimeField(help_text='Horário para administração da medicação', verbose_name='Horário')),
                ('duration', models.CharField(help_text='Período do tratamento (ex: 7 dias, contínuo)', max_length=100, verbose_name='Duração')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se a medicação está sendo administrada atualmente', verbose_name='Ativo')),
                ('resident', models.ForeignKey(help_text='Residente que toma a medicação', on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='residents.resident', verbose_name='Residente')),
            ],
            options={
                'verbose_name': 'Medicação',
                'verbose_name_plural': 'Medicações',
                'ordering': ['resident__name', 'schedule_time', 'name'],
            },
        ),
    ]
