# Generated by Django 4.2.11 on 2025-09-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(db_index=True, editable=False, verbose_name='Atualizado em')),
                ('name', models.CharField(help_text='Nome completo do residente', max_length=200, verbose_name='Nome')),
                ('date_of_birth', models.DateField(help_text='Data de nascimento do residente', verbose_name='Data de nascimento')),
                ('family_contact', models.CharField(help_text='Informações de contato da família', max_length=200, verbose_name='Contato familiar')),
                ('health_history', models.TextField(help_text='Histórico médico e condições de saúde', verbose_name='Histórico de saúde')),
                ('notes', models.TextField(blank=True, help_text='Observações gerais sobre o residente', verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Residente',
                'verbose_name_plural': 'Residentes',
                'ordering': ['name'],
            },
        ),
    ]
