# Generated by Django 4.2.11 on 2025-09-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='health_history',
            field=models.TextField(blank=True, help_text='Histórico médico e condições de saúde', null=True, verbose_name='Histórico de saúde'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='notes',
            field=models.TextField(blank=True, help_text='Observações gerais sobre o residente', null=True, verbose_name='Observações'),
        ),
    ]
