# Generated by Django 4.2.11 on 2025-09-21 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(db_index=True, editable=False, verbose_name='Atualizado em')),
                ('type', models.CharField(choices=[('appointment', 'Consulta'), ('exam', 'Exame')], help_text='Tipo de atendimento', max_length=20, verbose_name='Tipo')),
                ('description', models.TextField(help_text='Descrição da consulta ou exame', verbose_name='Descrição')),
                ('date_time', models.DateTimeField(help_text='Data e hora do atendimento', verbose_name='Data e hora')),
                ('status', models.CharField(choices=[('scheduled', 'Agendado'), ('completed', 'Concluído'), ('pending', 'Pendente')], default='scheduled', help_text='Status atual do atendimento', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, help_text='Observações sobre o atendimento', verbose_name='Observações')),
                ('resident', models.ForeignKey(help_text='Residente que terá a consulta ou exame', on_delete=django.db.models.deletion.CASCADE, related_name='appointments_exams', to='residents.resident', verbose_name='Residente')),
            ],
            options={
                'verbose_name': 'Consulta/Exame',
                'verbose_name_plural': 'Consultas/Exames',
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(db_index=True, editable=False, verbose_name='Atualizado em')),
                ('file', models.FileField(help_text='Arquivo do exame (PDF, imagem, etc.)', upload_to='exam_attachments/%Y/%m/', verbose_name='Arquivo')),
                ('description', models.CharField(blank=True, help_text='Descrição do arquivo', max_length=200, verbose_name='Descrição')),
                ('appointment_exam', models.ForeignKey(blank=True, help_text='Consulta ou exame ao qual o anexo pertence (opcional para exames não registrados)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='appointments.appointmentexam', verbose_name='Consulta/Exame')),
                ('resident', models.ForeignKey(help_text='Residente ao qual o exame pertence', on_delete=django.db.models.deletion.CASCADE, related_name='exam_attachments', to='residents.resident', verbose_name='Residente')),
            ],
            options={
                'verbose_name': 'Anexo de Exame',
                'verbose_name_plural': 'Anexos de Exames',
                'ordering': ['-created_at'],
            },
        ),
    ]
